"""initial schema

Revision ID: c04a107284c3
Revises: 
Create Date: 2026-07-25 22:45:22.348200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c04a107284c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('commission_plan_versions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_commission_plan_versions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_plan_versions'))
    )
    op.create_index(op.f('ix_commission_plan_versions_organization_id'), 'commission_plan_versions', ['organization_id'], unique=False)
    op.create_table('domain_outbox',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_domain_outbox_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_outbox'))
    )
    op.create_index(op.f('ix_domain_outbox_event_type'), 'domain_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_domain_outbox_organization_id'), 'domain_outbox', ['organization_id'], unique=False)
    op.create_index(op.f('ix_domain_outbox_processed_at'), 'domain_outbox', ['processed_at'], unique=False)
    op.create_table('network_snapshots',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_network_snapshots_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_snapshots'))
    )
    op.create_index(op.f('ix_network_snapshots_organization_id'), 'network_snapshots', ['organization_id'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('energy_type', sa.String(length=16), nullable=False),
    sa.Column('customer_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_products_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_table('ranks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('personal_token_cents', sa.BigInteger(), nullable=False),
    sa.Column('energy_share_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('personal_volume_threshold_cents', sa.BigInteger(), nullable=False),
    sa.Column('group_volume_threshold_cents', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_window_months', sa.Integer(), nullable=False),
    sa.Column('single_branch_cap_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ranks_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranks')),
    sa.UniqueConstraint('organization_id', 'code', 'rule_version', name='uq_ranks_org_code_version')
    )
    op.create_index(op.f('ix_ranks_organization_id'), 'ranks', ['organization_id'], unique=False)
    op.create_table('roles',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_roles_org_code')
    )
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('agent_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('promoter_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_rank_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_rank_id'], ['ranks.id'], name=op.f('fk_agent_profiles_current_rank_id_ranks')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_profiles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_profiles')),
    sa.UniqueConstraint('organization_id', 'promoter_code', name='uq_agent_promoter_code')
    )
    op.create_index(op.f('ix_agent_profiles_organization_id'), 'agent_profiles', ['organization_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_log_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_correlation_id'), 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_table('commission_rule_versions',
    sa.Column('commission_plan_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commission_plan_version_id'], ['commission_plan_versions.id'], name=op.f('fk_commission_rule_versions_commission_plan_version_id_commission_plan_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_rule_versions'))
    )
    op.create_index(op.f('ix_commission_rule_versions_commission_plan_version_id'), 'commission_rule_versions', ['commission_plan_version_id'], unique=False)
    op.create_table('customers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('fiscal_code', sa.String(length=32), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customers_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_customers_user_id'))
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('product_versions',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('base_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('initial_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('recurring_fee_cents', sa.BigInteger(), nullable=False),
    sa.Column('billing_period', sa.String(length=16), nullable=False),
    sa.Column('tax_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('commission_plan_version_id', sa.UUID(), nullable=True),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terms_version', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commission_plan_version_id'], ['commission_plan_versions.id'], name=op.f('fk_product_versions_commission_plan_version_id_commission_plan_versions')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_versions_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_versions'))
    )
    op.create_index(op.f('ix_product_versions_product_id'), 'product_versions', ['product_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_roles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'organization_id', 'role_id', name='uq_user_roles')
    )
    op.create_index(op.f('ix_user_roles_organization_id'), 'user_roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('addresses',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('province', sa.String(length=8), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_addresses_customer_id_customers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_addresses_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.create_index(op.f('ix_addresses_organization_id'), 'addresses', ['organization_id'], unique=False)
    op.create_table('agent_rank_history',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('rank_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculation_source', sa.String(length=32), nullable=False),
    sa.Column('rule_version_id', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], name=op.f('fk_agent_rank_history_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_agent_rank_history_approved_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_rank_history_organization_id_organizations')),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], name=op.f('fk_agent_rank_history_rank_id_ranks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_rank_history'))
    )
    op.create_index(op.f('ix_agent_rank_history_agent_id'), 'agent_rank_history', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_rank_history_organization_id'), 'agent_rank_history', ['organization_id'], unique=False)
    op.create_table('companies',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_form', sa.String(length=64), nullable=True),
    sa.Column('sdi_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_companies_customer_id_customers')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_companies'))
    )
    op.create_table('contract_attributions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('producer_agent_id', sa.UUID(), nullable=False),
    sa.Column('attributed_promoter_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attributed_promoter_id'], ['agent_profiles.id'], name=op.f('fk_contract_attributions_attributed_promoter_id_agent_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contract_attributions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['producer_agent_id'], ['agent_profiles.id'], name=op.f('fk_contract_attributions_producer_agent_id_agent_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_attributions'))
    )
    op.create_index(op.f('ix_contract_attributions_organization_id'), 'contract_attributions', ['organization_id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_profiles_customer_id_customers')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customer_profiles'))
    )
    op.create_table('network_assignment_history',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('old_parent_agent_id', sa.UUID(), nullable=True),
    sa.Column('new_parent_agent_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], name=op.f('fk_network_assignment_history_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_network_assignment_history_approved_by_users')),
    sa.ForeignKeyConstraint(['new_parent_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_assignment_history_new_parent_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['old_parent_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_assignment_history_old_parent_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_network_assignment_history_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_network_assignment_history_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_assignment_history'))
    )
    op.create_index(op.f('ix_network_assignment_history_organization_id'), 'network_assignment_history', ['organization_id'], unique=False)
    op.create_table('network_closure',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ancestor_agent_id', sa.UUID(), nullable=False),
    sa.Column('descendant_agent_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ancestor_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_closure_ancestor_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['descendant_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_closure_descendant_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_network_closure_organization_id_organizations')),
    sa.PrimaryKeyConstraint('organization_id', 'ancestor_agent_id', 'descendant_agent_id', 'effective_from', name=op.f('pk_network_closure'))
    )
    op.create_index('ix_network_closure_org_ancestor', 'network_closure', ['organization_id', 'ancestor_agent_id'], unique=False)
    op.create_index('ix_network_closure_org_ancestor_depth', 'network_closure', ['organization_id', 'ancestor_agent_id', 'depth'], unique=False)
    op.create_index('ix_network_closure_org_descendant', 'network_closure', ['organization_id', 'descendant_agent_id'], unique=False)
    op.create_index('ix_network_closure_org_descendant_depth', 'network_closure', ['organization_id', 'descendant_agent_id', 'depth'], unique=False)
    op.create_table('network_edges',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('parent_agent_id', sa.UUID(), nullable=False),
    sa.Column('child_agent_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_edges_child_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_network_edges_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_edges_parent_agent_id_agent_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_edges'))
    )
    op.create_index(op.f('ix_network_edges_child_agent_id'), 'network_edges', ['child_agent_id'], unique=False)
    op.create_index(op.f('ix_network_edges_organization_id'), 'network_edges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_network_edges_parent_agent_id'), 'network_edges', ['parent_agent_id'], unique=False)
    op.create_table('network_nodes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('direct_parent_agent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], name=op.f('fk_network_nodes_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['direct_parent_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_nodes_direct_parent_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_network_nodes_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_nodes'))
    )
    op.create_index(op.f('ix_network_nodes_agent_id'), 'network_nodes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_network_nodes_organization_id'), 'network_nodes', ['organization_id'], unique=False)
    op.create_index('uq_network_nodes_active_agent', 'network_nodes', ['organization_id', 'agent_id'], unique=True, postgresql_where=sa.text('effective_to IS NULL'))
    op.create_table('network_snapshot_nodes',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('ancestor_agent_id', sa.UUID(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('rank_id_at_snapshot', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ancestor_agent_id'], ['agent_profiles.id'], name=op.f('fk_network_snapshot_nodes_ancestor_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['rank_id_at_snapshot'], ['ranks.id'], name=op.f('fk_network_snapshot_nodes_rank_id_at_snapshot_ranks')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['network_snapshots.id'], name=op.f('fk_network_snapshot_nodes_snapshot_id_network_snapshots')),
    sa.PrimaryKeyConstraint('snapshot_id', 'ancestor_agent_id', name=op.f('pk_network_snapshot_nodes'))
    )
    op.create_table('promoter_codes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('personal_link', sa.String(length=500), nullable=False),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], name=op.f('fk_promoter_codes_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_promoter_codes_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promoter_codes'))
    )
    op.create_index(op.f('ix_promoter_codes_agent_id'), 'promoter_codes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_promoter_codes_code'), 'promoter_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promoter_codes_organization_id'), 'promoter_codes', ['organization_id'], unique=False)
    op.create_table('referral_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('promoter_code_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_referral_events_organization_id_organizations')),
    sa.ForeignKeyConstraint(['promoter_code_id'], ['promoter_codes.id'], name=op.f('fk_referral_events_promoter_code_id_promoter_codes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_events'))
    )
    op.create_index(op.f('ix_referral_events_organization_id'), 'referral_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_referral_events_promoter_code_id'), 'referral_events', ['promoter_code_id'], unique=False)
    op.create_table('referral_sessions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('promoter_code_id', sa.UUID(), nullable=False),
    sa.Column('cookie_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_referral_sessions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['promoter_code_id'], ['promoter_codes.id'], name=op.f('fk_referral_sessions_promoter_code_id_promoter_codes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_sessions'))
    )
    op.create_index(op.f('ix_referral_sessions_cookie_token_hash'), 'referral_sessions', ['cookie_token_hash'], unique=True)
    op.create_index(op.f('ix_referral_sessions_organization_id'), 'referral_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_referral_sessions_promoter_code_id'), 'referral_sessions', ['promoter_code_id'], unique=False)
    op.create_table('supply_points',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('energy_type', sa.String(length=16), nullable=False),
    sa.Column('pod_code', sa.String(length=32), nullable=True),
    sa.Column('pdr_code', sa.String(length=32), nullable=True),
    sa.Column('meter_number', sa.String(length=64), nullable=True),
    sa.Column('supply_address_id', sa.UUID(), nullable=False),
    sa.Column('estimated_consumption', sa.BigInteger(), nullable=True),
    sa.Column('actual_consumption', sa.BigInteger(), nullable=True),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_supply_points_customer_id_customers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_supply_points_organization_id_organizations')),
    sa.ForeignKeyConstraint(['supply_address_id'], ['addresses.id'], name=op.f('fk_supply_points_supply_address_id_addresses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supply_points'))
    )
    op.create_index(op.f('ix_supply_points_customer_id'), 'supply_points', ['customer_id'], unique=False)
    op.create_index(op.f('ix_supply_points_organization_id'), 'supply_points', ['organization_id'], unique=False)
    op.create_table('contracts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('supply_point_id', sa.UUID(), nullable=False),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('contract_attribution_id', sa.UUID(), nullable=True),
    sa.Column('network_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_attribution_id'], ['contract_attributions.id'], name=op.f('fk_contracts_contract_attribution_id_contract_attributions')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_contracts_customer_id_customers')),
    sa.ForeignKeyConstraint(['network_snapshot_id'], ['network_snapshots.id'], name=op.f('fk_contracts_network_snapshot_id_network_snapshots')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contracts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], name=op.f('fk_contracts_product_version_id_product_versions')),
    sa.ForeignKeyConstraint(['supply_point_id'], ['supply_points.id'], name=op.f('fk_contracts_supply_point_id_supply_points')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contracts_organization_id'), 'contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('customer_attributions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('promoter_code_id', sa.UUID(), nullable=False),
    sa.Column('referral_session_id', sa.UUID(), nullable=True),
    sa.Column('attributed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_attributions_customer_id_customers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customer_attributions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['promoter_code_id'], ['promoter_codes.id'], name=op.f('fk_customer_attributions_promoter_code_id_promoter_codes')),
    sa.ForeignKeyConstraint(['referral_session_id'], ['referral_sessions.id'], name=op.f('fk_customer_attributions_referral_session_id_referral_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_attributions'))
    )
    op.create_index(op.f('ix_customer_attributions_customer_id'), 'customer_attributions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_attributions_organization_id'), 'customer_attributions', ['organization_id'], unique=False)
    op.create_table('attribution_corrections',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_attribution_id', sa.UUID(), nullable=False),
    sa.Column('previous_promoter_code_id', sa.UUID(), nullable=False),
    sa.Column('new_promoter_code_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_attribution_corrections_approved_by_users')),
    sa.ForeignKeyConstraint(['customer_attribution_id'], ['customer_attributions.id'], name=op.f('fk_attribution_corrections_customer_attribution_id_customer_attributions')),
    sa.ForeignKeyConstraint(['new_promoter_code_id'], ['promoter_codes.id'], name=op.f('fk_attribution_corrections_new_promoter_code_id_promoter_codes')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attribution_corrections_organization_id_organizations')),
    sa.ForeignKeyConstraint(['previous_promoter_code_id'], ['promoter_codes.id'], name=op.f('fk_attribution_corrections_previous_promoter_code_id_promoter_codes')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_attribution_corrections_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribution_corrections'))
    )
    op.create_index(op.f('ix_attribution_corrections_organization_id'), 'attribution_corrections', ['organization_id'], unique=False)
    op.create_table('commission_calculations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('network_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('commission_plan_version_id', sa.UUID(), nullable=True),
    sa.Column('trigger_event_id', sa.UUID(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commission_plan_version_id'], ['commission_plan_versions.id'], name=op.f('fk_commission_calculations_commission_plan_version_id_commission_plan_versions')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_commission_calculations_contract_id_contracts')),
    sa.ForeignKeyConstraint(['network_snapshot_id'], ['network_snapshots.id'], name=op.f('fk_commission_calculations_network_snapshot_id_network_snapshots')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_commission_calculations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_calculations'))
    )
    op.create_index(op.f('ix_commission_calculations_contract_id'), 'commission_calculations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_commission_calculations_organization_id'), 'commission_calculations', ['organization_id'], unique=False)
    op.create_table('contract_events',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_contract_events_contract_id_contracts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_events'))
    )
    op.create_index(op.f('ix_contract_events_contract_id'), 'contract_events', ['contract_id'], unique=False)
    op.create_table('contract_status_history',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_contract_status_history_actor_user_id_users')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_contract_status_history_contract_id_contracts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_status_history'))
    )
    op.create_index(op.f('ix_contract_status_history_contract_id'), 'contract_status_history', ['contract_id'], unique=False)
    op.create_table('commission_calculation_steps',
    sa.Column('calculation_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('beneficiary_agent_id', sa.UUID(), nullable=False),
    sa.Column('rank_at_calculation', sa.String(length=16), nullable=True),
    sa.Column('base_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('already_distributed_cents', sa.BigInteger(), nullable=False),
    sa.Column('entrepreneurial_difference_cents', sa.BigInteger(), nullable=False),
    sa.Column('personal_bonus_cents', sa.BigInteger(), nullable=False),
    sa.Column('gross_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_agent_id'], ['agent_profiles.id'], name=op.f('fk_commission_calculation_steps_beneficiary_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['calculation_id'], ['commission_calculations.id'], name=op.f('fk_commission_calculation_steps_calculation_id_commission_calculations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_calculation_steps'))
    )
    op.create_index(op.f('ix_commission_calculation_steps_calculation_id'), 'commission_calculation_steps', ['calculation_id'], unique=False)
    op.create_table('commission_movements',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('origin_event_id', sa.UUID(), nullable=False),
    sa.Column('calculation_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('rule_version_id', sa.String(length=32), nullable=False),
    sa.Column('network_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_profiles.id'], name=op.f('fk_commission_movements_agent_id_agent_profiles')),
    sa.ForeignKeyConstraint(['calculation_id'], ['commission_calculations.id'], name=op.f('fk_commission_movements_calculation_id_commission_calculations')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_commission_movements_contract_id_contracts')),
    sa.ForeignKeyConstraint(['network_snapshot_id'], ['network_snapshots.id'], name=op.f('fk_commission_movements_network_snapshot_id_network_snapshots')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_commission_movements_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_movements')),
    sa.UniqueConstraint('idempotency_key', name='uq_commission_movements_idempotency_key')
    )
    op.create_index(op.f('ix_commission_movements_agent_id'), 'commission_movements', ['agent_id'], unique=False)
    op.create_index(op.f('ix_commission_movements_contract_id'), 'commission_movements', ['contract_id'], unique=False)
    op.create_index(op.f('ix_commission_movements_organization_id'), 'commission_movements', ['organization_id'], unique=False)
    op.create_table('commission_adjustments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('original_movement_id', sa.UUID(), nullable=False),
    sa.Column('new_movement_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_commission_adjustments_approved_by_users')),
    sa.ForeignKeyConstraint(['new_movement_id'], ['commission_movements.id'], name=op.f('fk_commission_adjustments_new_movement_id_commission_movements')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_commission_adjustments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['original_movement_id'], ['commission_movements.id'], name=op.f('fk_commission_adjustments_original_movement_id_commission_movements')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_commission_adjustments_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_adjustments'))
    )
    op.create_index(op.f('ix_commission_adjustments_organization_id'), 'commission_adjustments', ['organization_id'], unique=False)
    op.create_table('commission_offsets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('debit_movement_id', sa.UUID(), nullable=False),
    sa.Column('credit_movement_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_movement_id'], ['commission_movements.id'], name=op.f('fk_commission_offsets_credit_movement_id_commission_movements')),
    sa.ForeignKeyConstraint(['debit_movement_id'], ['commission_movements.id'], name=op.f('fk_commission_offsets_debit_movement_id_commission_movements')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_commission_offsets_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_offsets'))
    )
    op.create_index(op.f('ix_commission_offsets_organization_id'), 'commission_offsets', ['organization_id'], unique=False)
    op.create_table('commission_reversals',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('original_movement_id', sa.UUID(), nullable=False),
    sa.Column('new_movement_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_commission_reversals_approved_by_users')),
    sa.ForeignKeyConstraint(['new_movement_id'], ['commission_movements.id'], name=op.f('fk_commission_reversals_new_movement_id_commission_movements')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_commission_reversals_organization_id_organizations')),
    sa.ForeignKeyConstraint(['original_movement_id'], ['commission_movements.id'], name=op.f('fk_commission_reversals_original_movement_id_commission_movements')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_commission_reversals_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_reversals'))
    )
    op.create_index(op.f('ix_commission_reversals_organization_id'), 'commission_reversals', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commission_reversals_organization_id'), table_name='commission_reversals')
    op.drop_table('commission_reversals')
    op.drop_index(op.f('ix_commission_offsets_organization_id'), table_name='commission_offsets')
    op.drop_table('commission_offsets')
    op.drop_index(op.f('ix_commission_adjustments_organization_id'), table_name='commission_adjustments')
    op.drop_table('commission_adjustments')
    op.drop_index(op.f('ix_commission_movements_organization_id'), table_name='commission_movements')
    op.drop_index(op.f('ix_commission_movements_contract_id'), table_name='commission_movements')
    op.drop_index(op.f('ix_commission_movements_agent_id'), table_name='commission_movements')
    op.drop_table('commission_movements')
    op.drop_index(op.f('ix_commission_calculation_steps_calculation_id'), table_name='commission_calculation_steps')
    op.drop_table('commission_calculation_steps')
    op.drop_index(op.f('ix_contract_status_history_contract_id'), table_name='contract_status_history')
    op.drop_table('contract_status_history')
    op.drop_index(op.f('ix_contract_events_contract_id'), table_name='contract_events')
    op.drop_table('contract_events')
    op.drop_index(op.f('ix_commission_calculations_organization_id'), table_name='commission_calculations')
    op.drop_index(op.f('ix_commission_calculations_contract_id'), table_name='commission_calculations')
    op.drop_table('commission_calculations')
    op.drop_index(op.f('ix_attribution_corrections_organization_id'), table_name='attribution_corrections')
    op.drop_table('attribution_corrections')
    op.drop_index(op.f('ix_customer_attributions_organization_id'), table_name='customer_attributions')
    op.drop_index(op.f('ix_customer_attributions_customer_id'), table_name='customer_attributions')
    op.drop_table('customer_attributions')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_organization_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_supply_points_organization_id'), table_name='supply_points')
    op.drop_index(op.f('ix_supply_points_customer_id'), table_name='supply_points')
    op.drop_table('supply_points')
    op.drop_index(op.f('ix_referral_sessions_promoter_code_id'), table_name='referral_sessions')
    op.drop_index(op.f('ix_referral_sessions_organization_id'), table_name='referral_sessions')
    op.drop_index(op.f('ix_referral_sessions_cookie_token_hash'), table_name='referral_sessions')
    op.drop_table('referral_sessions')
    op.drop_index(op.f('ix_referral_events_promoter_code_id'), table_name='referral_events')
    op.drop_index(op.f('ix_referral_events_organization_id'), table_name='referral_events')
    op.drop_table('referral_events')
    op.drop_index(op.f('ix_promoter_codes_organization_id'), table_name='promoter_codes')
    op.drop_index(op.f('ix_promoter_codes_code'), table_name='promoter_codes')
    op.drop_index(op.f('ix_promoter_codes_agent_id'), table_name='promoter_codes')
    op.drop_table('promoter_codes')
    op.drop_table('network_snapshot_nodes')
    op.drop_index('uq_network_nodes_active_agent', table_name='network_nodes', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_index(op.f('ix_network_nodes_organization_id'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_agent_id'), table_name='network_nodes')
    op.drop_table('network_nodes')
    op.drop_index(op.f('ix_network_edges_parent_agent_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_organization_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_child_agent_id'), table_name='network_edges')
    op.drop_table('network_edges')
    op.drop_index('ix_network_closure_org_descendant_depth', table_name='network_closure')
    op.drop_index('ix_network_closure_org_descendant', table_name='network_closure')
    op.drop_index('ix_network_closure_org_ancestor_depth', table_name='network_closure')
    op.drop_index('ix_network_closure_org_ancestor', table_name='network_closure')
    op.drop_table('network_closure')
    op.drop_index(op.f('ix_network_assignment_history_organization_id'), table_name='network_assignment_history')
    op.drop_table('network_assignment_history')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_contract_attributions_organization_id'), table_name='contract_attributions')
    op.drop_table('contract_attributions')
    op.drop_table('companies')
    op.drop_index(op.f('ix_agent_rank_history_organization_id'), table_name='agent_rank_history')
    op.drop_index(op.f('ix_agent_rank_history_agent_id'), table_name='agent_rank_history')
    op.drop_table('agent_rank_history')
    op.drop_index(op.f('ix_addresses_organization_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_organization_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_product_versions_product_id'), table_name='product_versions')
    op.drop_table('product_versions')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_commission_rule_versions_commission_plan_version_id'), table_name='commission_rule_versions')
    op.drop_table('commission_rule_versions')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_correlation_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_profiles_organization_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_ranks_organization_id'), table_name='ranks')
    op.drop_table('ranks')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_network_snapshots_organization_id'), table_name='network_snapshots')
    op.drop_table('network_snapshots')
    op.drop_index(op.f('ix_domain_outbox_processed_at'), table_name='domain_outbox')
    op.drop_index(op.f('ix_domain_outbox_organization_id'), table_name='domain_outbox')
    op.drop_index(op.f('ix_domain_outbox_event_type'), table_name='domain_outbox')
    op.drop_table('domain_outbox')
    op.drop_index(op.f('ix_commission_plan_versions_organization_id'), table_name='commission_plan_versions')
    op.drop_table('commission_plan_versions')
    op.drop_table('permissions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
